"""Second Migration

Revision ID: 329fd3ad403c
Revises: c156784fea6a
Create Date: 2022-05-13 19:06:33.358450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '329fd3ad403c'
down_revision = 'c156784fea6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'pass_secure')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
