"""Add column

Revision ID: 35900b911e0b
Revises: 7733bb31428f
Create Date: 2022-05-13 19:16:08.288764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35900b911e0b'
down_revision = '7733bb31428f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###
