"""Another Migration

Revision ID: 7733bb31428f
Revises: 329fd3ad403c
Create Date: 2022-05-13 19:13:11.280753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7733bb31428f'
down_revision = '329fd3ad403c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
